export const icons = {
  back: require('./back.webp'),
  down: require('./down.webp'),
  right: require('./rightArrow.webp'),
  close: require('./close.webp'),
  check: require('./check.webp'),
  unchecked: require('./unchecked.webp'),
  approved: require('./approved.webp'),
  closefill: require('./closefill.webp'),
  checked: require('./checked.webp'),
  morning: require('./morning.webp'),
  evening: require('./evening.webp'),
  afternoon: require('./afternoon.webp'),
  // search: require('./search.webp'),
  finger: require('./finger.webp'),
  signin: require('./signin.webp'),
  signout: require('./signout.webp'),
  qr: require('./qr.webp'),
  dom: require('./dom.webp'),
  activity: require('./activity.webp'),
  profile: require('./profile.webp'),
  home: require('./home.webp'),
  search: require('./searchB.webp'),
  more: require('./more.webp'),
  notification: require('./notification.webp'),
  filledNoti: require('./filledNoti.webp'),
  filledHome: require('./filledHome.webp'),
  calenderView: require('./calenderView.webp'),
  meeting: require('./meeting.webp'),
  repeat: require('./repeat.webp'),
  time: require('./time.webp'),
  meetingIcon: require('./meetingIcon.webp'),
  plus: require('./plus.webp'),
  group: require('./group.webp'),
  verified: require('./verified.webp'),
  closed: require('./closed.webp'),
  del: require('./del.webp'),
  defaultIcons: require('./del.webp'),
  up: require('./up.webp'),
  downn: require('./downn.webp'),
  briefcase: require('./briefcase.webp'),
  calendar: require('./calendar.webp'),
  clock: require('./clock.webp'),
  menu: require('./menu.webp'),
  cross: require('./cross.webp'),
  circleCheck: require('./circleCheck.webp'),
  circleChecked: require('./circleChecked.webp'),
  pen: require('./pen.webp'),
  notes: require('./notes.png'),
  dob: require('./dateofbirth.png'),
  email: require('./email.png'),
  gender: require('./gender.png'),
  phone: require('./phone.png'),
  left: require('./left.png'),
  rightt: require('./right.png'),
  noConnection: require('./noConnection.png'),
  info: require('./info.png'),
};

export {default as Show} from './show.svg';
export {default as Hide} from './hide.svg';
export {default as Info} from './info.svg';
