import React from 'react';
import RawButton from './Button';
import RawText from './Text';
import RawInputField from './InputField';
import RawPagingDots from './Pagingdots';
import RawIcon from './Icon';
import RawHeader from './Header';
import RawSpinner from './Spinner';
import RawToast from './Toast';
import RawScannerMask from './ScannerMask';
import RawLoadingScreen from './Loading';
import RawModal from './Modal';
import RawDropdown from './Dropdown ';
import RawTimePicker from './TimePicker';
import RawSwitch from './Switch';
import RawCountdownTimer from './CountdownTimer';
import RawProfileAvatar from './ProfileAvatar';

export const Button = React.memo(RawButton);
export const Text = React.memo(RawText);
export const InputField = React.memo(RawInputField);
export const PaginationDots = React.memo(RawPagingDots);
export const Icon = React.memo(RawIcon);
export const Header = React.memo(RawHeader);
export const Spinner = React.memo(RawSpinner);
export const Toast = React.memo(RawToast);
export const QRScannerMask = React.memo(RawScannerMask);
export const LoadingScreen = React.memo(RawLoadingScreen);
export const Modal = React.memo(RawModal);
export const Dropdown = React.memo(RawDropdown);
export const TimePicker = React.memo(RawTimePicker);
export const Switch = React.memo(RawSwitch);
export const CountdownTimer = React.memo(RawCountdownTimer);
export const ProfileAvatar = React.memo(RawProfileAvatar);
